# Generated by Django 3.2.5 on 2022-06-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuber', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'Destination'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='slug',
        ),
    ]
