# Generated by Django 3.2.5 on 2022-06-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuber', '0002_auto_20220612_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='order_date',
            field=models.DateField(auto_now=True),
        ),
    ]
